<?php

function webprofiler_schema() {
  $schema['webprofiler_profiles'] = array(
    'description' => 'A table to store specific information about performance profiles so that they can be looked up more easily.',
    'fields' => array(
      'id' => array(
        'description' => 'A unique identifier for the profile.',
        'type' => 'varchar',
        'length' => 32,
        'not null' => TRUE,
        'default' => '',
      ),
      'path' => array(
        'description' => 'The url of the request for which the profile was generated.',
        'type' => 'varchar',
        'length' => 255,
        'not null' => TRUE,
        'default' => '',
      ),
      'timestamp' => array(
        'description' => 'The Unix timestamp when the profile was created.',
        'type' => 'int',
        'not null' => TRUE,
        'default' => 0,
      ),
      'time' => array(
        'description' => 'The execution time of the request.',
        'type' => 'float',
        'not null' => TRUE,
        'default' => 0,
      ),
      'peak_memory' => array(
        'description' => 'The highest amount of memory used during the request.',
        'type' => 'int',
        'not null' => TRUE,
        'default' => 0,
      ),
      'queries' => array(
        'description' => 'The number of queries executed during the request.',
        'type' => 'int',
        'not null' => TRUE,
        'default' => 0,
      ),
      'function_calls' => array(
        'description' => 'The number of function calls made during the request.',
        'type' => 'int',
        'not null' => TRUE,
        'default' => 0,
      ),
    ),
    'indexes' => array(
      'timestamp'        => array('timestamp'),
    ),
    'primary key' => array('id'),
  );
  return $schema;
}

function webprofiler_uninstall() {
  file_unmanaged_delete_recursive('public://webprofiler_profiles');
}
